
export const genres = [
  {id: '2', title:'Point and Click', backgroundColor:'#FDFFFC', fontColor: '#1E1C1D'},
  {id: '4', title:'Fighting', backgroundColor:'#3F0606', fontColor: '#FDFFFC'},
  {id: '5', title:'Shooter', backgroundColor:'#9753C6', fontColor: '#FDFFFC'},
  {id: '7', title:'Music', backgroundColor:'#F48AF0', fontColor: '#1E1C1D'},
  {id: '8', title:'Platform', backgroundColor:'#382020', fontColor: '#FDFFFC'},
  {id: '9', title:'Puzzle', backgroundColor:'#302F58', fontColor: '#FDFFFC'},
  {id: '10', title:'Racing', backgroundColor:'#00C2FF', fontColor: '#1E1C1D'},
  {id: '11', title:'RTS', backgroundColor:'#181EA6', fontColor: '#FDFFFC'},
  {id: '12', title:'RPG', backgroundColor:'#1F8023', fontColor: '#FDFFFC'},
  {id: '13', title:'Simulator', backgroundColor:'#EBD564', fontColor: '#1E1C1D'},
  {id: '14', title:'Sport', backgroundColor:'#166210', fontColor: '#FDFFFC'},
  {id: '15', title:'Strategy', backgroundColor:'#0386AF', fontColor: '#1E1C1D'},
  {id: '16', title:'TBS', backgroundColor:'#ffcb05', fontColor: '#1E1C1D'},
  {id: '24', title:'Tactical', backgroundColor:'#C8930C', fontColor: '#1E1C1D'},
  {id: '25', title:"Hack and slash", backgroundColor:'#B11F15', fontColor: '#FDFFFC'},
  {id: '26', title:'Trivia', backgroundColor:'#86C24A', fontColor: '#1E1C1D'},
  {id: '30', title:'Pinball', backgroundColor:'#8834C2', fontColor: '#FDFFFC'},
  {id: '31', title:'Adventure', backgroundColor:'#040F75', fontColor: '#FDFFFC'},
  {id: '32', title:'Indie', backgroundColor:'#25262F', fontColor: '#FDFFFC'},
  {id: '33', title:'Arcade', backgroundColor:'#DEEF1A', fontColor: '#1E1C1D'},
  {id: '34', title:'Visual Novel', backgroundColor:'#8C93DB', fontColor: '#1E1C1D'},
  {id: '35', title:'Card & Board Game', backgroundColor:'#FA8F8F', fontColor: '#1E1C1D'},
  {id: '36', title:'MOBA', backgroundColor:'#13181B', fontColor: '#FDFFFC'},
]